apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: twofold
  labels:
    app: twofold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twofold
  template:
    metadata:
      labels:
        app: twofold
    spec:
      containers:
      - name: twofold
        image: ghcr.io/alexfirilov/twofold:1770418180 # {"$imagepolicy": "flux-system:twofold"}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: twofold-config
        - secretRef:
            name: twofold-secrets
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
      imagePullSecrets:
      - name: ghcr-secret
