apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: our-little-corner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: our-little-corner
  template:
    metadata:
      labels:
        app: our-little-corner
    spec:
      containers:
      - name: our-little-corner
        image: ghcr.io/alexfirilolv/our_little_corner:1769698678 # {"$imagepolicy": "flux-system:our-little-corner"}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: our-little-corner-config
        - secretRef:
            name: our-little-corner-secrets
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
      imagePullSecrets:
      - name: ghcr-secret
