apiVersion: v1
kind: Service
metadata:
  name: our-little-corner-service
spec:
  type: ClusterIP
  selector:
    app: our-little-corner
  ports:
    - protocol: TCP
      port: 80
      targetPort : 3000
